Import ('env')

name = 'phylopp'
inc = env.Dir('.')
src = env.Glob('*.cpp')
deps = ['phylopp','gmock','gtest_main', 'gtest']
CXXFLAGS=['-Wall', '-Wextra', '-Wno-sign-compare']

env.Replace(CXXFLAGS=CXXFLAGS, CFLAGS=CXXFLAGS)
env.CreateTest(name, inc, src, deps)
